### PR TITLE
expose zstd filter to R

### PR DESCRIPTION
**Pull request by coolbutuseless**
Enable 'zstd' as a filter.

I'm unsure which exact ARCHIVE_VERSION_NUMBER this was added to libarchive, and I don't know how to find it out. So i've lumped it in with the same version number when LZ4 was added for now.

Any guidance appreciated.

### CODE REVIEW

**Comment by jimhester** [comment]
It was added in https://github.com/libarchive/libarchive/commit/f59fec02545917911a632ccff2d2305f0d65b401, which looks like it is only available in 3.3.3

So you need a `#if ARCHIVE_VERSION_NUMBER >= 3003003` define.

**Comment by coolbutuseless** [comment]
I tried adding ".zst" and ".tar.zst" to your suite of tests, but appveyor  said they failed, so I've removed them for now.  

any thoughts?

**Comment by jimhester** [comment]
It looks like you need to rebase this on the current master. Something like the following should get you there

```shell
# assumes my repo is called upstream and you are on your local zstd branch
git fetch upstream
git rebase -i upstream/master
# fix any rebase conflicts, add them and and git rebase --continue
git push --force-with-lease
```

**Comment by jimhester** [comment]
The windows archive binary is not built with support for zstandard, so it will not work. You will need to skip the tests if the archive version is older than 3.3.3.

**Pull request closed without merging**
